export const IQ_BY_COUNTRY = [
  { country: 'Japan', flag: '🇯🇵', iq: 106.49, rank: 1 },
  { country: 'Taiwan', flag: '🇹🇼', iq: 106.47, rank: 2 },
  { country: 'Singapore', flag: '🇸🇬', iq: 105.89, rank: 3 },
  { country: 'Hong Kong', flag: '🇭🇰', iq: 105.37, rank: 4 },
  { country: 'China', flag: '🇨🇳', iq: 104.10, rank: 5 },
  { country: 'South Korea', flag: '🇰🇷', iq: 102.35, rank: 6 },
  { country: 'Belarus', flag: '🇧🇾', iq: 101.60, rank: 7 },
  { country: 'Finland', flag: '🇫🇮', iq: 101.20, rank: 8 },
  { country: 'Germany', flag: '🇩🇪', iq: 100.74, rank: 9 },
  { country: 'Netherlands', flag: '🇳🇱', iq: 100.74, rank: 10 },
  { country: 'Austria', flag: '🇦🇹', iq: 100.16, rank: 11 },
  { country: 'Sweden', flag: '🇸🇪', iq: 99.73, rank: 12 },
  { country: 'Switzerland', flag: '🇨🇭', iq: 99.25, rank: 13 },
  { country: 'United Kingdom', flag: '🇬🇧', iq: 99.12, rank: 14 },
  { country: 'Norway', flag: '🇳🇴', iq: 98.45, rank: 15 },
  { country: 'Canada', flag: '🇨🇦', iq: 97.96, rank: 16 },
  { country: 'Australia', flag: '🇦🇺', iq: 97.74, rank: 17 },
  { country: 'Czech Republic', flag: '🇨🇿', iq: 97.70, rank: 18 },
  { country: 'Denmark', flag: '🇩🇰', iq: 97.24, rank: 19 },
  { country: 'France', flag: '🇫🇷', iq: 97.23, rank: 20 },
  { country: 'United States', flag: '🇺🇸', iq: 97.43, rank: 21 },
  { country: 'Russia', flag: '🇷🇺', iq: 96.29, rank: 25 },
  { country: 'Spain', flag: '🇪🇸', iq: 96.04, rank: 27 },
  { country: 'Italy', flag: '🇮🇹', iq: 95.90, rank: 28 },
  { country: 'Brazil', flag: '🇧🇷', iq: 84.38, rank: 55 },
]

export const IQ_BY_US_STATE = [
  { state: 'Massachusetts', abbr: 'MA', iq: 104.3, rank: 1 },
  { state: 'New Hampshire', abbr: 'NH', iq: 104.2, rank: 2 },
  { state: 'Vermont', abbr: 'VT', iq: 103.8, rank: 3 },
  { state: 'Connecticut', abbr: 'CT', iq: 103.7, rank: 4 },
  { state: 'New Jersey', abbr: 'NJ', iq: 103.7, rank: 5 },
  { state: 'Washington', abbr: 'WA', iq: 103.6, rank: 6 },
  { state: 'California', abbr: 'CA', iq: 103.2, rank: 7 },
  { state: 'Minnesota', abbr: 'MN', iq: 103.1, rank: 8 },
  { state: 'Virginia', abbr: 'VA', iq: 102.8, rank: 9 },
  { state: 'Maryland', abbr: 'MD', iq: 102.7, rank: 10 },
  { state: 'Colorado', abbr: 'CO', iq: 102.4, rank: 11 },
  { state: 'Oregon', abbr: 'OR', iq: 102.2, rank: 12 },
  { state: 'Wisconsin', abbr: 'WI', iq: 102.0, rank: 13 },
  { state: 'Michigan', abbr: 'MI', iq: 101.8, rank: 14 },
  { state: 'Iowa', abbr: 'IA', iq: 101.7, rank: 15 },
  { state: 'Kansas', abbr: 'KS', iq: 101.4, rank: 16 },
  { state: 'Nebraska', abbr: 'NE', iq: 101.2, rank: 17 },
  { state: 'Utah', abbr: 'UT', iq: 101.0, rank: 18 },
  { state: 'Idaho', abbr: 'ID', iq: 100.8, rank: 19 },
  { state: 'Wyoming', abbr: 'WY', iq: 100.7, rank: 20 },
  { state: 'Montana', abbr: 'MT', iq: 100.6, rank: 21 },
  { state: 'Ohio', abbr: 'OH', iq: 100.4, rank: 22 },
  { state: 'North Dakota', abbr: 'ND', iq: 100.3, rank: 23 },
  { state: 'South Dakota', abbr: 'SD', iq: 100.1, rank: 24 },
  { state: 'Pennsylvania', abbr: 'PA', iq: 100.0, rank: 25 },
  { state: 'Illinois', abbr: 'IL', iq: 99.8, rank: 26 },
  { state: 'Indiana', abbr: 'IN', iq: 99.5, rank: 27 },
  { state: 'New York', abbr: 'NY', iq: 99.4, rank: 28 },
  { state: 'Missouri', abbr: 'MO', iq: 99.2, rank: 29 },
  { state: 'Maine', abbr: 'ME', iq: 99.1, rank: 30 },
  { state: 'Rhode Island', abbr: 'RI', iq: 99.0, rank: 31 },
  { state: 'Arizona', abbr: 'AZ', iq: 98.8, rank: 32 },
  { state: 'Texas', abbr: 'TX', iq: 98.5, rank: 33 },
  { state: 'Georgia', abbr: 'GA', iq: 98.3, rank: 34 },
  { state: 'North Carolina', abbr: 'NC', iq: 98.1, rank: 35 },
  { state: 'Tennessee', abbr: 'TN', iq: 97.9, rank: 36 },
  { state: 'Kentucky', abbr: 'KY', iq: 97.7, rank: 37 },
  { state: 'Florida', abbr: 'FL', iq: 97.4, rank: 38 },
  { state: 'Nevada', abbr: 'NV', iq: 97.2, rank: 39 },
  { state: 'South Carolina', abbr: 'SC', iq: 97.0, rank: 40 },
  { state: 'Delaware', abbr: 'DE', iq: 96.9, rank: 41 },
  { state: 'Oklahoma', abbr: 'OK', iq: 96.8, rank: 42 },
  { state: 'Arkansas', abbr: 'AR', iq: 96.5, rank: 43 },
  { state: 'Alaska', abbr: 'AK', iq: 96.4, rank: 44 },
  { state: 'West Virginia', abbr: 'WV', iq: 96.2, rank: 45 },
  { state: 'Alabama', abbr: 'AL', iq: 95.9, rank: 46 },
  { state: 'Louisiana', abbr: 'LA', iq: 95.7, rank: 47 },
  { state: 'Hawaii', abbr: 'HI', iq: 95.5, rank: 48 },
  { state: 'New Mexico', abbr: 'NM', iq: 95.3, rank: 49 },
  { state: 'Mississippi', abbr: 'MS', iq: 94.2, rank: 50 },
]

export const IQ_BY_AGE = [
  { range: 'Under 16', avgIQ: 101, description: 'Still developing cognitive baseline' },
  { range: '16–17', avgIQ: 108, description: 'Peak fluid intelligence begins' },
  { range: '18–19', avgIQ: 105, description: 'Early adulthood adjustment' },
  { range: '20–24', avgIQ: 99, description: 'Stabilizing after school structure' },
  { range: '25–34', avgIQ: 104, description: 'Benefit from real-world experience' },
  { range: '35–44', avgIQ: 113, description: 'Peak crystallized intelligence' },
  { range: '45–54', avgIQ: 106, description: 'Strong verbal and reasoning skills' },
  { range: '55–64', avgIQ: 109, description: 'Wisdom and pattern recognition' },
  { range: '65+', avgIQ: 114, description: 'Highly experienced test-takers' },
]
